
services:
  frontend:
    image: ghcr.io/danielatanasovski/led-clock-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback

networks:
  bridge:
    driver: bridge
